### ISSUE TITLE
scanner:  `test_last_line` do not make sense

### ISSUE THREAD

**Issue by vincenzopalazzo** [lnspec-tools/lncodegen#7]
last line of what? and also the line that you are parsing are the same of `test_middle_line`

**Comment by michiboo** [comment]
there are 3 lines in the message, so test_last_line test if the last(3rd) line is parse correctly and test middle line test if the 2nd lines parse correctly

**Comment by vincenzopalazzo** [comment]
You should be add this in the code, I was not able to understand what the test do

**Comment by vincenzopalazzo** [comment]
and also, better test name can be useful too?
